config/routes.rb
Rails.application.routes.draw do
  root to: "tasks#index"

  resources :users, only: [:new, :create, :show, :update]
  namespace :admin do
    resources :users
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :tasks do
    collection do
      get 'close_to_deadline'
    end
  end
  resources :labeling, only: [:create, :destroy]
  resources :labels, only: [:index, :new, :create, :edit, :update, :destroy]
end

app/models/label.rb
class Label < ApplicationRecord
  has_many :labelings, dependent: :destroy
  has_many :tasks, through: :labelings, source: :task
  belongs_to :user
  enum color: %i[green blue red orange]
  enum shape: %i[ellipse square arrow]
  validates :title, presence: true, length: {maximum: 15}
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  before_action :set_label, only: %i[show edit update destroy]

  def index
    @labels = current_user.labels
  end
  def new
    @label = Label.new
  end
  def edit
  end
  def create
    @label = current_user.labels.build(label_params)
    if @label.save
      flash[:notice] = "ラベルを作成しました！"
      redirect_to labels_path
    else
      render :new
    end
  end
  def update
    if @label.update(label_params)
      flash[:notice] = "ラベルを編集しました！"
      redirect_to labels_path
    else
      render :edit
    end
  end
  def destroy
    @label.destroy
    flash[:notice] = "ラベルを削除しました！"
    redirect_to labels_url
  end

  private
  def set_label
    @label = Label.find(params[:id])
  end
  def label_params
    params.require(:label).permit(:title, :color, :shape)
  end
end

app/helpers/labels_helper.rb
module LabelsHelper
  def label_color(label)
    if label.green?
      "color_green"
    elsif label.blue?
      "color_blue"
    elsif label.red?
      "color_red"
    elsif label.orange?
      "color_orange"
    end
  end
  def label_shape(label)
    if label.ellipse?
      "shape_ellipse"
    elsif label.square?
      "shape_square"
    elsif label.arrow?
      if label.green?
        "shape_arrow_green"
      elsif label.blue?
        "shape_arrow_blue"
      elsif label.red?
        "shape_arrow_red"
      elsif label.orange?
        "shape_arrow_orange"
      end
    end
  end
end

app/views/labels/_form.html.erb
<%= form_with(model: label, local: true) do |form| %>
  <% if label.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(label.errors.count, "error") %> prohibited this label from being saved:</h2>

      <ul>
      <% label.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title, t('label.column.title') %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :color, t('label.column.color') %>
    <%= form.select :color, Label.enum_options_for_select(:color) %>
  </div>

  <div class="field">
    <%= form.label :shape, t('label.column.shape') %>
    <%= form.select :shape, Label.enum_options_for_select(:shape) %>
  </div>

  <div class="actions">
    <%= form.submit t('label.submit') %>
  </div>
<% end %>

app/views/labels/edit.html.erb
<div class="container">
  <h1><%= t('label.title.edit') %></h1>
  <%= render 'form', label: @label %>
  <%= link_to t('label.link.show'), @label %> |
  <%= link_to t('label.link.index'), labels_path %>
</div>

app/views/labels/index.html.erb
<div class="container">
  <h1><%= t('label.title.index') %></h1>
  <table class="container table table-bordered table-hover">
    <thead>
      <tr>
        <th><%= t('label.column.title') %></th>
        <th><%= t('label.column.color') %></th>
        <th><%= t('label.column.shape') %></th>
        <th colspan="2"><%= t('label.link.table') %></th>
      </tr>
    </thead>

    <tbody>
      <% @labels.each do |label| %>
        <tr>
          <td><%= label.title %></td>
          <td><%= label.human_attribute_enum(:color) %></td>
          <td><%= label.human_attribute_enum(:shape) %></td>
          <td><%= link_to t('label.link.edit'), edit_label_path(label) %></td>
          <td><%= link_to t('label.link.destroy'), label, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <%= link_to t('label.link.new'), new_label_path %>
</div>

app/views/labels/new.html.erb
<div class="container">
  <h1><%= t('label.title.new') %></h1>
  <%= render 'form', label: @label %>
  <%= link_to t('label.link.index'), labels_path %>
</div>