config/routes.rb
Rails.application.routes.draw do
  root to: "tasks#index"

  resources :users, only: [:new, :create, :show, :update]
  namespace :admin do
    resources :users
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :tasks do
    collection do
      get 'close_to_deadline'
    end
  end
  resources :labeling, only: [:create, :destroy]
  resources :labels, only: [:index, :new, :create, :edit, :update, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks, dependent: :delete_all
  has_many :labels, dependent: :delete_all

  before_validation {email.downcase!}
  before_destroy :destroy_ensure_admin
  before_update :update_ensure_admin

  validates :name, presence: true, length: {maximum: 30}
  validates :email, presence: true, length: {maximum: 90}, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password, presence: true, length: {minimum: 6}
  has_secure_password

  private
  def update_ensure_admin
    throw(:abort) if self.admin == false && User.where(admin: true).one?
  end
  def destroy_ensure_admin
    throw(:abort) if self.admin == true && User.where(admin: true).one?
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :prohibit_user_access
  def index
    @users = User.all.includes(:tasks)
  end
  def new
    @user = User.new
  end
  def show
    @user = User.find(params[:id])
  end
  def edit
    @user = User.find(params[:id])
  end
  def destroy
    @user = User.find(params[:id]).destroy
    flash[:notice] = "ユーザを削除しました！"
    redirect_to admin_users_path
  end
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  def prohibit_user_access
    unless current_user.admin
      redirect_to tasks_path
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user, only: %i[new create update]
  before_action :prohibit_signup, only: :new
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      @user.labels.build(title: "safe", color: "blue", shape: "square").save
      @user.labels.build(title: "danger", color: "red", shape: "arrow").save
      flash[:notice] = "ユーザ登録しました！"
      if logged_in?
        redirect_to admin_users_path
      else
        session[:user_id] = @user.id
        redirect_to user_path(@user.id)
      end
    else
      if logged_in?
        render 'admin/users/new'
      else
        render :new
      end
    end
  end
  def show
    @user = User.find(params[:id])
    prohibit_other_profiles
  end
  def update
    if logged_in? && current_user.admin
      @user = User.find(params[:id])
      if @user.update(user_params)
        flash[:notice] = "ユーザ情報を更新しました！"
        redirect_to admin_user_path
      else
        render 'admin/users/edit'
      end
    else
      redirect_to tasks_path
    end
  end
  def destroy
    @user = User.find(params[:id]).destroy
    flash[:notice] = "ユーザを削除しました！"
    redirect_to admin_users_path
  end
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
  end
  def prohibit_other_profiles
    if current_user.id != @user.id
      redirect_to tasks_path
    end
  end
  def prohibit_signup
    redirect_to user_path(current_user.id) if logged_in?
  end
end

app/views/users/new.html.erb
<h1><%= t('user.title.new') %></h1>
<%= form_with(model: @user, local: true) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :name, t('user.column.name') %><br>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label :email, t('user.column.email') %><br>
    <%= form.email_field :email %>
  </div>
  <div class="field">
    <%= form.label :password, t('user.column.password') %><br>
    <%= form.password_field :password %>
  </div>
  <div class="field">
    <%= form.label :password_field, t('user.column.password_confirmation') %><br>
    <%= form.password_field :password_field %>
  </div>
  <%= form.submit t('user.submit') %>
<% end %>

app/views/users/show.html.erb
<div class="container">
  <h1><%= t('user.title.show') %></h1>
  <div class="field">
    <%= t('user.column.name') %>: <%= @user.name %>
  </div>
  <div class="field">
    <%= t('user.column.email') %>: <%= @user.email %>
  </div>
  <div>
    <%= link_to t('task.link.index'), tasks_path %>|
    <%= link_to t('task.link.new'), new_task_path %><br>
    <%= link_to t('label.link.index'), labels_path %>|
    <%= link_to t('label.link.new'), new_label_path %><br>
    <% if current_user.admin %>
      <%= link_to t('admin.link.index'), admin_users_path %>
    <% end %>
  </div>
</div>