config/routes.rb
Rails.application.routes.draw do
  root to: "tasks#index"

  resources :users, only: [:new, :create, :show, :update]
  namespace :admin do
    resources :users
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :tasks do
    collection do
      get 'close_to_deadline'
    end
  end
  resources :labeling, only: [:create, :destroy]
  resources :labels, only: [:index, :new, :create, :edit, :update, :destroy]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManagement</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in? %>
      <%= link_to t('session.header.profile'), user_path(current_user.id) %>
      <%= link_to t('session.header.logout'), session_path(current_user.id), method: :delete %>
      <% if current_user.tasks.select{|task| (task.deadline - Time.current) / (60 * 60 * 24) <= 3 && task.status != t('task.status.completed')}.present? %>
        <%= link_to "終了期限間近(3日以内)なタスクがあります！", close_to_deadline_tasks_path %>
      <% end %>
    <% else %>
      <%= link_to t('session.header.signup'), new_user_path %>
      <%= link_to t('session.header.login'), new_session_path %>
    <% end %>
    <div class="flash_message">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>